---
resources:
- name: resource-version
  type: semver
  source:
    driver: git
    uri: git@github.com:mbarzare/concourse-tutorial 
    initial_version: 0.0.1
    branch: version
    file: 20_versions_and_buildnumbers/version
    private_key: {{github-private-key}}

jobs:
- name: job-versioning
  public: true
  serial: true
  plan:
  - put: resource-version
    params: {bump: patch}
